name: CI Docker Build

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Build da imagem do Backend
        run: docker build -t sistema-login-backend ./backend

      - name: Build da imagem do Frontend
        run: docker build -t sistema-login-frontend ./frontend
        